syntax = "proto3";

package lq;

import "cli_game.proto";
import "cli_lobby.proto";
import "cli_route.proto";
import "com_struct.proto";

service FastTest {
  rpc authGame (.lq.ReqAuthGame) returns (.lq.ResAuthGame);
  rpc authObserve (.lq.ReqAuthObserve) returns (.lq.ResCommon);
  rpc broadcastInGame (.lq.ReqBroadcastInGame) returns (.lq.ResCommon);
  rpc checkNetworkDelay (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc clearLeaving (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc confirmNewRound (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc enterGame (.lq.ReqCommon) returns (.lq.ResEnterGame);
  rpc fetchGamePlayerState (.lq.ReqCommon) returns (.lq.ResGamePlayerState);
  rpc finishSyncGame (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc inputChiPengGang (.lq.ReqChiPengGang) returns (.lq.ResCommon);
  rpc inputGameGMCommand (.lq.ReqGMCommandInGaming) returns (.lq.ResCommon);
  rpc inputOperation (.lq.ReqSelfOperation) returns (.lq.ResCommon);
  rpc startObserve (.lq.ReqCommon) returns (.lq.ResStartObserve);
  rpc stopObserve (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc syncGame (.lq.ReqSyncGame) returns (.lq.ResSyncGame);
  rpc terminateGame (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc voteGameEnd (.lq.ReqVoteGameEnd) returns (.lq.ResGameEndVote);
}

service Lobby {
  rpc addCollectedGameRecord (.lq.ReqAddCollectedGameRecord) returns (.lq.ResAddCollectedGameRecord);
  rpc addFinishedEnding (.lq.ReqFinishedEnding) returns (.lq.ResCommon);
  rpc addRoomRobot (.lq.ReqAddRoomRobot) returns (.lq.ResCommon);
  rpc amuletActivityFetchBrief (.lq.ReqAmuletActivityFetchBrief) returns (.lq.ResAmuletActivityFetchBrief);
  rpc amuletActivityGameOperate (.lq.ReqAmuletActivityGameOperate) returns (.lq.ResAmuletEventResponse);
  rpc amuletActivityGiveup (.lq.ReqAmuletActivityGiveup) returns (.lq.ResCommon);
  rpc amuletActivityMaintainInfo (.lq.ReqCommon) returns (.lq.ResAmuletActivityMaintainInfo);
  rpc amuletActivityOperate (.lq.ReqAmuletActivityOperate) returns (.lq.ResAmuletEventResponse);
  rpc amuletActivitySelectBookEffect (.lq.ReqAmuletActivitySelectBookEffect) returns (.lq.ResCommon);
  rpc amuletActivitySetSkillLevel (.lq.ReqAmuletActivitySetSkillLevel) returns (.lq.ResCommon);
  rpc amuletActivityStartGame (.lq.ReqAmuletActivityStartGame) returns (.lq.ResAmuletEventResponse);
  rpc applyFriend (.lq.ReqApplyFriend) returns (.lq.ResCommon);
  rpc bindAccount (.lq.ReqBindAccount) returns (.lq.ResCommon);
  rpc bindEmail (.lq.ReqBindEmail) returns (.lq.ResCommon);
  rpc bindOauth2 (.lq.ReqBindOauth2) returns (.lq.ResCommon);
  rpc bindPhoneNumber (.lq.ReqBindPhoneNumber) returns (.lq.ResCommon);
  rpc bingoActivityReceiveReward (.lq.ReqBingoActivityReceiveReward) returns (.lq.ResBingoActivityReceiveReward);
  rpc buyArenaTicket (.lq.ReqBuyArenaTicket) returns (.lq.ResCommon);
  rpc buyFestivalProposal (.lq.ReqBuyFestivalProposal) returns (.lq.ResBuyFestivalProposal);
  rpc buyFromChestShop (.lq.ReqBuyFromChestShop) returns (.lq.ResBuyFromChestShop);
  rpc buyFromShop (.lq.ReqBuyFromShop) returns (.lq.ResBuyFromShop);
  rpc buyFromZHP (.lq.ReqBuyFromZHP) returns (.lq.ResCommon);
  rpc buyInABMatch (.lq.ReqBuyInABMatch) returns (.lq.ResCommon);
  rpc buyShiLian (.lq.ReqBuyShiLian) returns (.lq.ResCommon);
  rpc cancelDeleteAccount (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc cancelGooglePlayOrder (.lq.ReqCancelGooglePlayOrder) returns (.lq.ResCommon);
  rpc cancelMatch (.lq.ReqCancelMatchQueue) returns (.lq.ResCommon);
  rpc cancelQueue (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc cancelUnifiedMatch (.lq.ReqCancelUnifiedMatch) returns (.lq.ResCommon);
  rpc changeAvatar (.lq.ReqChangeAvatar) returns (.lq.ResCommon);
  rpc changeCharacterSkin (.lq.ReqChangeCharacterSkin) returns (.lq.ResCommon);
  rpc changeCharacterView (.lq.ReqChangeCharacterView) returns (.lq.ResCommon);
  rpc changeCollectedGameRecordRemarks (.lq.ReqChangeCollectedGameRecordRemarks) returns (.lq.ResChangeCollectedGameRecordRemarks);
  rpc changeCommonView (.lq.ReqChangeCommonView) returns (.lq.ResCommon);
  rpc changeMainCharacter (.lq.ReqChangeMainCharacter) returns (.lq.ResCommon);
  rpc checkPrivacy (.lq.ReqCheckPrivacy) returns (.lq.ResCommon);
  rpc clientMessage (.lq.ReqClientMessage) returns (.lq.ResCommon);
  rpc combiningRecycleCraft (.lq.ReqCombiningRecycleCraft) returns (.lq.ResCombiningRecycleCraft);
  rpc completeActivityFlipTask (.lq.ReqCompleteActivityTask) returns (.lq.ResCommon);
  rpc completeActivityFlipTaskBatch (.lq.ReqCompleteActivityFlipTaskBatch) returns (.lq.ResCompleteActivityFlipTaskBatch);
  rpc completeActivityTask (.lq.ReqCompleteActivityTask) returns (.lq.ResCommon);
  rpc completeActivityTaskBatch (.lq.ReqCompleteActivityTaskBatch) returns (.lq.ResCommon);
  rpc completePeriodActivityTask (.lq.ReqCompleteActivityTask) returns (.lq.ResCommon);
  rpc completePeriodActivityTaskBatch (.lq.ReqCompletePeriodActivityTaskBatch) returns (.lq.ResCommon);
  rpc completeRandomActivityTask (.lq.ReqCompleteActivityTask) returns (.lq.ResCommon);
  rpc completeRandomActivityTaskBatch (.lq.ReqCompleteActivityTaskBatch) returns (.lq.ResCommon);
  rpc completeSegmentTaskReward (.lq.ReqCompleteSegmentTaskReward) returns (.lq.ResCompleteSegmentTaskReward);
  rpc completeVillageTask (.lq.ReqCompleteVillageTask) returns (.lq.ResCompleteVillageTask);
  rpc composeShard (.lq.ReqComposeShard) returns (.lq.ResCommon);
  rpc createAlipayAppOrder (.lq.ReqCreateAlipayAppOrder) returns (.lq.ResCreateAlipayAppOrder);
  rpc createAlipayOrder (.lq.ReqCreateAlipayOrder) returns (.lq.ResCreateAlipayOrder);
  rpc createAlipayScanOrder (.lq.ReqCreateAlipayScanOrder) returns (.lq.ResCreateAlipayScanOrder);
  rpc createBillingOrder (.lq.ReqCreateBillingOrder) returns (.lq.ResCreateBillingOrder);
  rpc createCustomizedContest (.lq.ReqCreateCustomizedContest) returns (.lq.ResCreateCustomizedContest);
  rpc createDMMOrder (.lq.ReqCreateDMMOrder) returns (.lq.ResCreateDmmOrder);
  rpc createENAlipayOrder (.lq.ReqCreateENAlipayOrder) returns (.lq.ResCreateENAlipayOrder);
  rpc createENJCBOrder (.lq.ReqCreateENJCBOrder) returns (.lq.ResCreateENJCBOrder);
  rpc createENMasterCardOrder (.lq.ReqCreateENMasterCardOrder) returns (.lq.ResCreateENMasterCardOrder);
  rpc createENPaypalOrder (.lq.ReqCreateENPaypalOrder) returns (.lq.ResCreateENPaypalOrder);
  rpc createENVisaOrder (.lq.ReqCreateENVisaOrder) returns (.lq.ResCreateENVisaOrder);
  rpc createEmailVerifyCode (.lq.ReqCreateEmailVerifyCode) returns (.lq.ResCommon);
  rpc createGameObserveAuth (.lq.ReqCreateGameObserveAuth) returns (.lq.ResCreateGameObserveAuth);
  rpc createGamePlan (.lq.ReqCreateGamePlan) returns (.lq.ResCommon);
  rpc createIAPOrder (.lq.ReqCreateIAPOrder) returns (.lq.ResCreateIAPOrder);
  rpc createJPAuOrder (.lq.ReqCreateJPAuOrder) returns (.lq.ResCreateJPAuOrder);
  rpc createJPCreditCardOrder (.lq.ReqCreateJPCreditCardOrder) returns (.lq.ResCreateJPCreditCardOrder);
  rpc createJPDocomoOrder (.lq.ReqCreateJPDocomoOrder) returns (.lq.ResCreateJPDocomoOrder);
  rpc createJPGMOOrder (.lq.ReqCreateJPGMOOrder) returns (.lq.ResCreateJPGMOOrder);
  rpc createJPPayPayOrder (.lq.ReqCreateJPPayPayOrder) returns (.lq.ResCreateJPPayPayOrder);
  rpc createJPPaypalOrder (.lq.ReqCreateJPPaypalOrder) returns (.lq.ResCreateJPPaypalOrder);
  rpc createJPSoftbankOrder (.lq.ReqCreateJPSoftbankOrder) returns (.lq.ResCreateJPSoftbankOrder);
  rpc createJPWebMoneyOrder (.lq.ReqCreateJPWebMoneyOrder) returns (.lq.ResCreateJPWebMoneyOrder);
  rpc createKRAlipayOrder (.lq.ReqCreateKRAlipayOrder) returns (.lq.ResCreateKRAlipayOrder);
  rpc createKRJCBOrder (.lq.ReqCreateKRJCBOrder) returns (.lq.ResCreateKRJCBOrder);
  rpc createKRMasterCardOrder (.lq.ReqCreateKRMasterCardOrder) returns (.lq.ResCreateKRMasterCardOrder);
  rpc createKRPaypalOrder (.lq.ReqCreateKRPaypalOrder) returns (.lq.ResCreateKRPaypalOrder);
  rpc createKRVisaOrder (.lq.ReqCreateKRVisaOrder) returns (.lq.ResCreateKRVisaOrder);
  rpc createMyCardAndroidOrder (.lq.ReqCreateMyCardOrder) returns (.lq.ResCreateMyCardOrder);
  rpc createMyCardWebOrder (.lq.ReqCreateMyCardOrder) returns (.lq.ResCreateMyCardOrder);
  rpc createNickname (.lq.ReqCreateNickname) returns (.lq.ResCommon);
  rpc createPaypalOrder (.lq.ReqCreatePaypalOrder) returns (.lq.ResCreatePaypalOrder);
  rpc createPhoneLoginBind (.lq.ReqCreatePhoneLoginBind) returns (.lq.ResCommon);
  rpc createPhoneVerifyCode (.lq.ReqCreatePhoneVerifyCode) returns (.lq.ResCommon);
  rpc createRoom (.lq.ReqCreateRoom) returns (.lq.ResCreateRoom);
  rpc createSeerReport (.lq.ReqCreateSeerReport) returns (.lq.ResCreateSeerReport);
  rpc createSteamOrder (.lq.ReqCreateSteamOrder) returns (.lq.ResCreateSteamOrder);
  rpc createWechatAppOrder (.lq.ReqCreateWechatAppOrder) returns (.lq.ResCreateWechatAppOrder);
  rpc createWechatNativeOrder (.lq.ReqCreateWechatNativeOrder) returns (.lq.ResCreateWechatNativeOrder);
  rpc createXsollaOrder (.lq.ReqCreateXsollaOrder) returns (.lq.ResCreateXsollaOrder);
  rpc createXsollaV4Order (.lq.ReqCreateXsollaOrder) returns (.lq.ResCreateXsollaOrder);
  rpc createYostarSDKOrder (.lq.ReqCreateYostarOrder) returns (.lq.ResCreateYostarOrder);
  rpc createYostarV4SDKOrder (.lq.ReqCreateYostarV4SDKOrder) returns (.lq.ResCreateYostarV4SDKOrder);
  rpc deleteAccount (.lq.ReqCommon) returns (.lq.ResDeleteAccount);
  rpc deleteComment (.lq.ReqDeleteComment) returns (.lq.ResCommon);
  rpc deleteMail (.lq.ReqDeleteMail) returns (.lq.ResCommon);
  rpc deliverAA32Order (.lq.ReqDeliverAA32Order) returns (.lq.ResCommon);
  rpc digMine (.lq.ReqDigMine) returns (.lq.ResDigMine);
  rpc dmmPreLogin (.lq.ReqDMMPreLogin) returns (.lq.ResDMMPreLogin);
  rpc doActivitySignIn (.lq.ReqDoActivitySignIn) returns (.lq.ResDoActivitySignIn);
  rpc doDailySignIn (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc dressingStatus (.lq.ReqRoomDressing) returns (.lq.ResCommon);
  rpc emailLogin (.lq.ReqEmailLogin) returns (.lq.ResLogin);
  rpc enterArena (.lq.ReqEnterArena) returns (.lq.ResCommon);
  rpc enterCustomizedContest (.lq.ReqEnterCustomizedContest) returns (.lq.ResEnterCustomizedContest);
  rpc exchangeActivityItem (.lq.ReqExchangeActivityItem) returns (.lq.ResExchangeActivityItem);
  rpc exchangeChestStone (.lq.ReqExchangeCurrency) returns (.lq.ResCommon);
  rpc exchangeCurrency (.lq.ReqExchangeCurrency) returns (.lq.ResCommon);
  rpc exchangeDiamond (.lq.ReqExchangeCurrency) returns (.lq.ResCommon);
  rpc fastLogin (.lq.ReqFastLogin) returns (.lq.ResFastLogin);
  rpc feedActivityFeed (.lq.ReqFeedActivityFeed) returns (.lq.ResFeedActivityFeed);
  rpc fetchABMatchInfo (.lq.ReqCommon) returns (.lq.ResFetchABMatch);
  rpc fetchAccountActivityData (.lq.ReqCommon) returns (.lq.ResAccountActivityData);
  rpc fetchAccountChallengeRankInfo (.lq.ReqAccountInfo) returns (.lq.ResAccountChallengeRankInfo);
  rpc fetchAccountCharacterInfo (.lq.ReqCommon) returns (.lq.ResAccountCharacterInfo);
  rpc fetchAccountGameHuRecords (.lq.ReqFetchAccountGameHuRecords) returns (.lq.ResFetchAccountGameHuRecords);
  rpc fetchAccountInfo (.lq.ReqAccountInfo) returns (.lq.ResAccountInfo);
  rpc fetchAccountInfoExtra (.lq.ReqFetchAccountInfoExtra) returns (.lq.ResFetchAccountInfoExtra);
  rpc fetchAccountSettings (.lq.ReqCommon) returns (.lq.ResAccountSettings);
  rpc fetchAccountState (.lq.ReqAccountList) returns (.lq.ResAccountStates);
  rpc fetchAccountStatisticInfo (.lq.ReqAccountStatisticInfo) returns (.lq.ResAccountStatisticInfo);
  rpc fetchAchievement (.lq.ReqCommon) returns (.lq.ResAchievement);
  rpc fetchAchievementRate (.lq.ReqCommon) returns (.lq.ResFetchAchievementRate);
  rpc fetchActivityBuff (.lq.ReqCommon) returns (.lq.ResActivityBuff);
  rpc fetchActivityFlipInfo (.lq.ReqFetchActivityFlipInfo) returns (.lq.ResFetchActivityFlipInfo);
  rpc fetchActivityInterval (.lq.ReqCommon) returns (.lq.ResFetchActivityInterval);
  rpc fetchActivityList (.lq.ReqCommon) returns (.lq.ResActivityList);
  rpc fetchActivityRank (.lq.ReqFetchActivityRank) returns (.lq.ResFetchActivityRank);
  rpc fetchAllCommonViews (.lq.ReqCommon) returns (.lq.ResAllcommonViews);
  rpc fetchAmuletActivityData (.lq.ReqFetchAmuletActivityData) returns (.lq.ResFetchAmuletActivityData);
  rpc fetchAnnouncement (.lq.ReqFetchAnnouncement) returns (.lq.ResAnnouncement);
  rpc fetchAnnualReportInfo (.lq.ReqCommon) returns (.lq.ResFetchAnnualReportInfo);
  rpc fetchBagInfo (.lq.ReqCommon) returns (.lq.ResBagInfo);
  rpc fetchBannerActivityData (.lq.ReqFetchBannerActivityData) returns (.lq.ResFetchBannerActivityData);
  rpc fetchBingoActivityData (.lq.ReqFetchBingoActivityData) returns (.lq.ResFetchBingoActivityData);
  rpc fetchChallengeInfo (.lq.ReqCommon) returns (.lq.ResFetchChallengeInfo);
  rpc fetchChallengeLeaderboard (.lq.ReqChallangeLeaderboard) returns (.lq.ResChallengeLeaderboard);
  rpc fetchChallengeSeason (.lq.ReqCommon) returns (.lq.ResChallengeSeasonInfo);
  rpc fetchCharacterInfo (.lq.ReqCommon) returns (.lq.ResCharacterInfo);
  rpc fetchClientValue (.lq.ReqCommon) returns (.lq.ResClientValue);
  rpc fetchCollectedGameRecordList (.lq.ReqCommon) returns (.lq.ResCollectedGameRecordList);
  rpc fetchCommentContent (.lq.ReqFetchCommentContent) returns (.lq.ResFetchCommentContent);
  rpc fetchCommentList (.lq.ReqFetchCommentList) returns (.lq.ResFetchCommentList);
  rpc fetchCommentSetting (.lq.ReqCommon) returns (.lq.ResCommentSetting);
  rpc fetchCommonView (.lq.ReqCommon) returns (.lq.ResCommonView);
  rpc fetchCommonViews (.lq.ReqCommonViews) returns (.lq.ResCommonViews);
  rpc fetchConnectionInfo (.lq.ReqCommon) returns (.lq.ResConnectionInfo);
  rpc fetchContestPlayerRank (.lq.ReqFetchContestPlayerRank) returns (.lq.ResFetchContestPlayerRank);
  rpc fetchContestTeamMember (.lq.ReqFetchContestTeamMember) returns (.lq.ResFetchContestTeamMember);
  rpc fetchContestTeamPlayerRank (.lq.ReqFetchContestTeamPlayerRank) returns (.lq.ResFetchContestPlayerRank);
  rpc fetchContestTeamRank (.lq.ReqFetchContestTeamRank) returns (.lq.ResFetchContestTeamRank);
  rpc fetchCurrentMatchInfo (.lq.ReqCurrentMatchInfo) returns (.lq.ResCurrentMatchInfo);
  rpc fetchCustomizedContestAuthInfo (.lq.ReqFetchCustomizedContestAuthInfo) returns (.lq.ResFetchCustomizedContestAuthInfo);
  rpc fetchCustomizedContestByContestId (.lq.ReqFetchCustomizedContestByContestId) returns (.lq.ResFetchCustomizedContestByContestId);
  rpc fetchCustomizedContestGameLiveList (.lq.ReqFetchCustomizedContestGameLiveList) returns (.lq.ResFetchCustomizedContestGameLiveList);
  rpc fetchCustomizedContestGameRecords (.lq.ReqFetchCustomizedContestGameRecords) returns (.lq.ResFetchCustomizedContestGameRecords);
  rpc fetchCustomizedContestList (.lq.ReqFetchCustomizedContestList) returns (.lq.ResFetchCustomizedContestList);
  rpc fetchCustomizedContestOnlineInfo (.lq.ReqFetchCustomizedContestOnlineInfo) returns (.lq.ResFetchCustomizedContestOnlineInfo);
  rpc fetchDailySignActivityData (.lq.ReqFetchDailySignActivityData) returns (.lq.ResFetchDailySignActivityData);
  rpc fetchDailySignInInfo (.lq.ReqCommon) returns (.lq.ResDailySignInInfo);
  rpc fetchDailyTask (.lq.ReqCommon) returns (.lq.ResDailyTask);
  rpc fetchFriendApplyList (.lq.ReqCommon) returns (.lq.ResFriendApplyList);
  rpc fetchFriendGiftActivityData (.lq.ReqFetchFriendGiftActivityData) returns (.lq.ResFetchFriendGiftActivityData);
  rpc fetchFriendList (.lq.ReqCommon) returns (.lq.ResFriendList);
  rpc fetchGameLiveInfo (.lq.ReqGameLiveInfo) returns (.lq.ResGameLiveInfo);
  rpc fetchGameLiveLeftSegment (.lq.ReqGameLiveLeftSegment) returns (.lq.ResGameLiveLeftSegment);
  rpc fetchGameLiveList (.lq.ReqGameLiveList) returns (.lq.ResGameLiveList);
  rpc fetchGamePointRank (.lq.ReqGamePointRank) returns (.lq.ResGamePointRank);
  rpc fetchGameRecord (.lq.ReqGameRecord) returns (.lq.ResGameRecord);
  rpc fetchGameRecordList (.lq.ReqGameRecordList) returns (.lq.ResGameRecordList);
  rpc fetchGameRecordListV2 (.lq.ReqGameRecordListV2) returns (.lq.ResGameRecordListV2);
  rpc fetchGameRecordsDetail (.lq.ReqGameRecordsDetail) returns (.lq.ResGameRecordsDetail);
  rpc fetchGameRecordsDetailV2 (.lq.ReqGameRecordsDetailV2) returns (.lq.ResGameRecordsDetailV2);
  rpc fetchGamingInfo (.lq.ReqCommon) returns (.lq.ResFetchGamingInfo);
  rpc fetchIDCardInfo (.lq.ReqCommon) returns (.lq.ResIDCardInfo);
  rpc fetchInfo (.lq.ReqCommon) returns (.lq.ResFetchInfo);
  rpc fetchJPCommonCreditCardOrder (.lq.ReqFetchJPCommonCreditCardOrder) returns (.lq.ResFetchJPCommonCreditCardOrder);
  rpc fetchLastPrivacy (.lq.ReqFetchLastPrivacy) returns (.lq.ResFetchLastPrivacy);
  rpc fetchLevelLeaderboard (.lq.ReqLevelLeaderboard) returns (.lq.ResLevelLeaderboard);
  rpc fetchMailInfo (.lq.ReqCommon) returns (.lq.ResMailInfo);
  rpc fetchMaintainNotice (.lq.ReqCommon) returns (.lq.ResFetchMaintainNotice);
  rpc fetchManagerCustomizedContest (.lq.ReqFetchManagerCustomizedContest) returns (.lq.ResFetchManagerCustomizedContest);
  rpc fetchManagerCustomizedContestList (.lq.ReqFetchmanagerCustomizedContestList) returns (.lq.ResFetchManagerCustomizedContestList);
  rpc fetchMisc (.lq.ReqCommon) returns (.lq.ResMisc);
  rpc fetchModNicknameTime (.lq.ReqCommon) returns (.lq.ResModNicknameTime);
  rpc fetchMonthTicketInfo (.lq.ReqCommon) returns (.lq.ResMonthTicketInfo);
  rpc fetchMultiAccountBrief (.lq.ReqMultiAccountId) returns (.lq.ResMultiAccountBrief);
  rpc fetchMutiChallengeLevel (.lq.ReqMutiChallengeLevel) returns (.lq.ResMutiChallengeLevel);
  rpc fetchNextGameRecordList (.lq.ReqNextGameRecordList) returns (.lq.ResNextGameRecordList);
  rpc fetchOBToken (.lq.ReqFetchOBToken) returns (.lq.ResFetchOBToken);
  rpc fetchOauth2Info (.lq.ReqFetchOauth2) returns (.lq.ResFetchOauth2);
  rpc fetchPhoneLoginBind (.lq.ReqCommon) returns (.lq.ResFetchPhoneLoginBind);
  rpc fetchPlatformProducts (.lq.ReqPlatformBillingProducts) returns (.lq.ResPlatformBillingProducts);
  rpc fetchProgressRewardActivityInfo (.lq.ReqFetchProgressRewardActivityInfo) returns (.lq.ResFetchProgressRewardActivityInfo);
  rpc fetchQuestionnaireDetail (.lq.ReqFetchQuestionnaireDetail) returns (.lq.ResFetchQuestionnaireDetail);
  rpc fetchQuestionnaireList (.lq.ReqFetchQuestionnaireList) returns (.lq.ResFetchQuestionnaireList);
  rpc fetchQueueInfo (.lq.ReqCommon) returns (.lq.ResFetchQueueInfo);
  rpc fetchRPGBattleHistory (.lq.ReqFetchRPGBattleHistory) returns (.lq.ResFetchRPGBattleHistory);
  rpc fetchRPGBattleHistoryV2 (.lq.ReqFetchRPGBattleHistory) returns (.lq.ResFetchRPGBattleHistoryV2);
  rpc fetchRandomCharacter (.lq.ReqCommon) returns (.lq.ResRandomCharacter);
  rpc fetchRankPointLeaderboard (.lq.ReqFetchRankPointLeaderboard) returns (.lq.ResFetchRankPointLeaderboard);
  rpc fetchReadyPlayerList (.lq.ReqFetchReadyPlayerList) returns (.lq.ResFetchReadyPlayerList);
  rpc fetchRecentFriend (.lq.ReqCommon) returns (.lq.ResFetchrecentFriend);
  rpc fetchRechargeInfo (.lq.ReqCommon) returns (.lq.ResFetchRechargeInfo);
  rpc fetchRefundOrder (.lq.ReqCommon) returns (.lq.ResFetchRefundOrder);
  rpc fetchReviveCoinInfo (.lq.ReqCommon) returns (.lq.ResReviveCoinInfo);
  rpc fetchRollingNotice (.lq.ReqFetchRollingNotice) returns (.lq.ResFetchRollingNotice);
  rpc fetchRoom (.lq.ReqCommon) returns (.lq.ResSelfRoom);
  rpc fetchSeerInfo (.lq.ReqCommon) returns (.lq.ResFetchSeerInfo);
  rpc fetchSeerReport (.lq.ReqFetchSeerReport) returns (.lq.ResFetchSeerReport);
  rpc fetchSeerReportList (.lq.ReqCommon) returns (.lq.ResFetchSeerReportList);
  rpc fetchSelfGamePointRank (.lq.ReqGamePointRank) returns (.lq.ResFetchSelfGamePointRank);
  rpc fetchServerMaintenanceInfo (.lq.ReqCommon) returns (.lq.ResFetchServerMaintenanceInfo);
  rpc fetchServerSettings (.lq.ReqCommon) returns (.lq.ResServerSettings);
  rpc fetchServerTime (.lq.ReqCommon) returns (.lq.ResServerTime);
  rpc fetchShopInfo (.lq.ReqCommon) returns (.lq.ResShopInfo);
  rpc fetchShopInterval (.lq.ReqCommon) returns (.lq.ResFetchShopInterval);
  rpc fetchSimulationGameRank (.lq.ReqFetchSimulationGameRank) returns (.lq.ResFetchSimulationGameRank);
  rpc fetchSimulationGameRecord (.lq.ReqFetchSimulationGameRecord) returns (.lq.ResFetchSimulationGameRecord);
  rpc fetchTitleList (.lq.ReqCommon) returns (.lq.ResTitleList);
  rpc fetchVipReward (.lq.ReqCommon) returns (.lq.ResVipReward);
  rpc fetchVoteActivity (.lq.ReqFetchVoteActivity) returns (.lq.ResFetchVoteActivity);
  rpc finishCombiningOrder (.lq.ReqFinishCombiningOrder) returns (.lq.ResFinishCombiningOrder);
  rpc followCustomizedContest (.lq.ReqTargetCustomizedContest) returns (.lq.ResCommon);
  rpc forceCompleteChallengeTask (.lq.ReqForceCompleteChallengeTask) returns (.lq.ResCommon);
  rpc gainAccumulatedPointActivityReward (.lq.ReqGainAccumulatedPointActivityReward) returns (.lq.ResCommon);
  rpc gainMultiPointActivityReward (.lq.ReqGainMultiPointActivityReward) returns (.lq.ResCommon);
  rpc gainRankPointReward (.lq.ReqGainRankPointReward) returns (.lq.ResCommon);
  rpc gainReviveCoin (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc gainVipReward (.lq.ReqGainVipReward) returns (.lq.ResCommon);
  rpc gameMasterCommand (.lq.ReqGMCommand) returns (.lq.ResCommon);
  rpc generateAnnualReportToken (.lq.ReqGenerateAnnualReportToken) returns (.lq.ResGenerateAnnualReportToken);
  rpc generateCombiningCraft (.lq.ReqGenerateCombiningCraft) returns (.lq.ResGenerateCombiningCraft);
  rpc generateContestManagerLoginCode (.lq.ReqCommon) returns (.lq.ResGenerateContestManagerLoginCode);
  rpc getFriendVillageData (.lq.ReqGetFriendVillageData) returns (.lq.ResGetFriendVillageData);
  rpc goNextShiLian (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc handleFriendApply (.lq.ReqHandleFriendApply) returns (.lq.ResCommon);
  rpc heatbeat (.lq.ReqHeatBeat) returns (.lq.ResCommon);
  rpc islandActivityBuy (.lq.ReqIslandActivityBuy) returns (.lq.ResCommon);
  rpc islandActivityMove (.lq.ReqIslandActivityMove) returns (.lq.ResCommon);
  rpc islandActivitySell (.lq.ReqIslandActivitySell) returns (.lq.ResCommon);
  rpc islandActivityTidyBag (.lq.ReqIslandActivityTidyBag) returns (.lq.ResCommon);
  rpc islandActivityUnlockBagGrid (.lq.ReqIslandActivityUnlockBagGrid) returns (.lq.ResCommon);
  rpc joinCustomizedContestChatRoom (.lq.ReqJoinCustomizedContestChatRoom) returns (.lq.ResJoinCustomizedContestChatRoom);
  rpc joinRoom (.lq.ReqJoinRoom) returns (.lq.ResJoinRoom);
  rpc leaveComment (.lq.ReqLeaveComment) returns (.lq.ResCommon);
  rpc leaveCustomizedContest (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc leaveCustomizedContestChatRoom (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc leaveRoom (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc likeSNS (.lq.ReqLikeSNS) returns (.lq.ResLikeSNS);
  rpc logReport (.lq.ReqLogReport) returns (.lq.ResCommon);
  rpc login (.lq.ReqLogin) returns (.lq.ResLogin);
  rpc loginBeat (.lq.ReqLoginBeat) returns (.lq.ResCommon);
  rpc loginSuccess (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc logout (.lq.ReqLogout) returns (.lq.ResLogout);
  rpc majClubActivityFetchData (.lq.ReqMajClubActivityFetchData) returns (.lq.ResMajClubActivityFetchData);
  rpc majClubActivityFinishDay (.lq.ReqMajClubActivityFinishDay) returns (.lq.ResMajClubActivityFinishDay);
  rpc majClubActivitySaveRoomData (.lq.ReqMajClubActivitySaveRoomData) returns (.lq.ResMajClubActivityCommon);
  rpc majClubActivityStartDay (.lq.ReqMajClubActivityStartDay) returns (.lq.ResMajClubActivityStartDay);
  rpc majClubActivityUnlockDesktop (.lq.ReqMajClubActivityUnlockDesktop) returns (.lq.ResMajClubActivityCommon);
  rpc majClubActivityUnlockRoom (.lq.ReqMajClubActivityUnlockRoom) returns (.lq.ResMajClubActivityCommon);
  rpc majClubActivityUpgradeCharacterPower (.lq.ReqMajClubActivityUpgradeCharacterPower) returns (.lq.ResMajClubActivityCommon);
  rpc majClubActivityUpgradeCharacterTag (.lq.ReqMajClubActivityUpgradeCharacterTag) returns (.lq.ResMajClubActivityCommon);
  rpc majClubActivityUpgradeRoomFee (.lq.ReqMajClubActivityUpgradeRoomFee) returns (.lq.ResMajClubActivityCommon);
  rpc majClubActivityUpgradeWaiting (.lq.ReqMajClubActivityUpgradeWaiting) returns (.lq.ResMajClubActivityCommon);
  rpc marathonActivityFinishRace (.lq.ReqMarathonActivityFinishRace) returns (.lq.ResMarathonActivityFinishRace);
  rpc marathonActivityStartRace (.lq.ReqMarathonActivityStartRace) returns (.lq.ResMarathonActivityStartRace);
  rpc matchGame (.lq.ReqJoinMatchQueue) returns (.lq.ResCommon);
  rpc matchShiLian (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc mmoActivityDebugSetTeamCandidate (.lq.ReqMMOActivityDebugSetTeamCandidate) returns (.lq.ResMMOActivityDebugSetTeamCandidate);
  rpc mmoActivityEquipFusion (.lq.ReqMMOActivityEquipFusion) returns (.lq.ResMMOActivityEquipFusion);
  rpc mmoActivityFetchData (.lq.ReqMMOActivityFetchData) returns (.lq.ResMMOActivityFetchData);
  rpc mmoActivityFinishBattle (.lq.ReqMMOActivityFinishBattle) returns (.lq.ResMMOActivityFinishBattle);
  rpc mmoActivityReceiveSupportReward (.lq.ReqMMOActivityReceiveSupportReward) returns (.lq.ResMMOActivityReceiveSupportReward);
  rpc mmoActivitySetCharacter (.lq.ReqMMOActivitySetCharacter) returns (.lq.ResMMOActivitySetCharacter);
  rpc mmoActivitySetEquip (.lq.ReqMMOActivitySetEquip) returns (.lq.ResMMOActivitySetEquip);
  rpc mmoActivitySetTeamMember (.lq.ReqMMOActivitySetTeamMember) returns (.lq.ResMMOActivitySetTeamMember);
  rpc mmoActivityStartBattle (.lq.ReqMMOActivityStartBattle) returns (.lq.ResMMOActivityStartBattle);
  rpc mmoActivityUpdateFriendList (.lq.ReqMMOActivityUpdatehFriendList) returns (.lq.ResMMOActivityUpdatehFriendList);
  rpc modifyBirthday (.lq.ReqModifyBirthday) returns (.lq.ResCommon);
  rpc modifyNickname (.lq.ReqModifyNickname) returns (.lq.ResCommon);
  rpc modifyPassword (.lq.ReqModifyPassword) returns (.lq.ResCommon);
  rpc modifyRoom (.lq.ReqModifyRoom) returns (.lq.ResCommon);
  rpc modifySignature (.lq.ReqModifySignature) returns (.lq.ResCommon);
  rpc moveCombiningCraft (.lq.ReqMoveCombiningCraft) returns (.lq.ResMoveCombiningCraft);
  rpc nextRoundVillage (.lq.ReqNextRoundVillage) returns (.lq.ResNextRoundVillage);
  rpc oauth2Auth (.lq.ReqOauth2Auth) returns (.lq.ResOauth2Auth);
  rpc oauth2Check (.lq.ReqOauth2Check) returns (.lq.ResOauth2Check);
  rpc oauth2Login (.lq.ReqOauth2Login) returns (.lq.ResLogin);
  rpc oauth2Signup (.lq.ReqOauth2Signup) returns (.lq.ResOauth2Signup);
  rpc openAllRewardItem (.lq.ReqOpenAllRewardItem) returns (.lq.ResOpenAllRewardItem);
  rpc openChest (.lq.ReqOpenChest) returns (.lq.ResOpenChest);
  rpc openGacha (.lq.ReqOpenGacha) returns (.lq.ResOpenGacha);
  rpc openManualItem (.lq.ReqOpenManualItem) returns (.lq.ResCommon);
  rpc openPreChestItem (.lq.ReqOpenPreChestItem) returns (.lq.ResOpenPreChestItem);
  rpc openRandomRewardItem (.lq.ReqOpenRandomRewardItem) returns (.lq.ResOpenRandomRewardItem);
  rpc openidCheck (.lq.ReqOpenidCheck) returns (.lq.ResOauth2Check);
  rpc payMonthTicket (.lq.ReqCommon) returns (.lq.ResPayMonthTicket);
  rpc prepareLogin (.lq.ReqPrepareLogin) returns (.lq.ResCommon);
  rpc progressRewardActivityReceive (.lq.ReqProgressRewardActivityReceive) returns (.lq.ResProgressRewardActivityReceive);
  rpc questCrewActivityFeed (.lq.ReqQuestCrewActivityFeed) returns (.lq.ResQuestCrewActivityFeed);
  rpc questCrewActivityHire (.lq.ReqQuestCrewActivityHire) returns (.lq.ResQuestCrewActivityHire);
  rpc questCrewActivityRefreshMarket (.lq.ReqQuestCrewActivityRefreshMarket) returns (.lq.ResQuestCrewActivityRefreshMarket);
  rpc questCrewActivityStartQuest (.lq.ReqQuestCrewActivityStartQuest) returns (.lq.ResQuestCrewActivityStartQuest);
  rpc quitABMatch (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc readAnnouncement (.lq.ReqReadAnnouncement) returns (.lq.ResCommon);
  rpc readGameRecord (.lq.ReqGameRecord) returns (.lq.ResCommon);
  rpc readMail (.lq.ReqReadMail) returns (.lq.ResCommon);
  rpc readSNS (.lq.ReqReadSNS) returns (.lq.ResReadSNS);
  rpc readyPlay (.lq.ReqRoomReady) returns (.lq.ResCommon);
  rpc receiveABMatchReward (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc receiveAchievementGroupReward (.lq.ReqReceiveAchievementGroupReward) returns (.lq.ResReceiveAchievementGroupReward);
  rpc receiveAchievementReward (.lq.ReqReceiveAchievementReward) returns (.lq.ResReceiveAchievementReward);
  rpc receiveActivityFlipTask (.lq.ReqReceiveActivityFlipTask) returns (.lq.ResReceiveActivityFlipTask);
  rpc receiveActivityFlipTaskBatch (.lq.ReqReceiveActivityFlipTaskBatch) returns (.lq.ResReceiveActivityFlipTaskBatch);
  rpc receiveActivityGift (.lq.ReqReceiveActivityGift) returns (.lq.ResCommon);
  rpc receiveActivitySpotReward (.lq.ReqReceiveActivitySpotReward) returns (.lq.ResReceiveActivitySpotReward);
  rpc receiveAllActivityGift (.lq.ReqReceiveAllActivityGift) returns (.lq.ResReceiveAllActivityGift);
  rpc receiveArenaReward (.lq.ReqArenaReward) returns (.lq.ResArenaReward);
  rpc receiveChallengeRankReward (.lq.ReqReceiveChallengeRankReward) returns (.lq.ResReceiveChallengeRankReward);
  rpc receiveCharacterRewards (.lq.ReqReceiveCharacterRewards) returns (.lq.ResReceiveCharacterRewards);
  rpc receiveEndingReward (.lq.ReqFinishedEnding) returns (.lq.ResCommon);
  rpc receiveRPGReward (.lq.ReqReceiveRPGReward) returns (.lq.ResReceiveRPGRewards);
  rpc receiveRPGRewards (.lq.ReqReceiveRPGRewards) returns (.lq.ResReceiveRPGRewards);
  rpc receiveUpgradeActivityReward (.lq.ReqReceiveUpgradeActivityReward) returns (.lq.ResReceiveUpgradeActivityReward);
  rpc receiveVersionReward (.lq.ReqCommon) returns (.lq.ResCommon);
  rpc receiveVillageBuildingReward (.lq.ReqReceiveVillageBuildingReward) returns (.lq.ResReceiveVillageBuildingReward);
  rpc receiveVillageTripReward (.lq.ReqReceiveVillageTripReward) returns (.lq.ResReceiveVillageTripReward);
  rpc recoverCombiningRecycle (.lq.ReqRecoverCombiningRecycle) returns (.lq.ResRecoverCombiningRecycle);
  rpc refreshChallenge (.lq.ReqCommon) returns (.lq.ResRefreshChallenge);
  rpc refreshDailyTask (.lq.ReqRefreshDailyTask) returns (.lq.ResRefreshDailyTask);
  rpc refreshGameObserveAuth (.lq.ReqRefreshGameObserveAuth) returns (.lq.ResRefreshGameObserveAuth);
  rpc refreshZHPShop (.lq.ReqReshZHPShop) returns (.lq.ResRefreshZHPShop);
  rpc remarkFriend (.lq.ReqRemarkFriend) returns (.lq.ResCommon);
  rpc removeCollectedGameRecord (.lq.ReqRemoveCollectedGameRecord) returns (.lq.ResRemoveCollectedGameRecord);
  rpc removeFriend (.lq.ReqRemoveFriend) returns (.lq.ResCommon);
  rpc replySNS (.lq.ReqReplySNS) returns (.lq.ResReplySNS);
  rpc resolveFestivalActivityEvent (.lq.ReqResolveFestivalActivityEvent) returns (.lq.ResResolveFestivalActivityEvent);
  rpc resolveFestivalActivityProposal (.lq.ReqResolveFestivalActivityProposal) returns (.lq.ResResolveFestivalActivityProposal);
  rpc richmanAcitivitySpecialMove (.lq.ReqRichmanSpecialMove) returns (.lq.ResRichmanNextMove);
  rpc richmanActivityChestInfo (.lq.ReqRichmanChestInfo) returns (.lq.ResRichmanChestInfo);
  rpc richmanActivityNextMove (.lq.ReqRichmanNextMove) returns (.lq.ResRichmanNextMove);
  rpc roomKickPlayer (.lq.ReqRoomKickPlayer) returns (.lq.ResCommon);
  rpc saveCommonViews (.lq.ReqSaveCommonViews) returns (.lq.ResCommon);
  rpc sayChatMessage (.lq.ReqSayChatMessage) returns (.lq.ResCommon);
  rpc searchAccountByEid (.lq.ReqSearchAccountByEidLobby) returns (.lq.ResSearchAccountbyEidLobby);
  rpc searchAccountById (.lq.ReqSearchAccountById) returns (.lq.ResSearchAccountById);
  rpc searchAccountByPattern (.lq.ReqSearchAccountByPattern) returns (.lq.ResSearchAccountByPattern);
  rpc selectChestChooseGroupActivity (.lq.ReqSelectChestChooseGroupActivity) returns (.lq.ResCommon);
  rpc selectChestChooseUpActivity (.lq.ReqSelectChestChooseUp) returns (.lq.ResCommon);
  rpc sellItem (.lq.ReqSellItem) returns (.lq.ResCommon);
  rpc sendActivityGiftToFriend (.lq.ReqSendActivityGiftToFriend) returns (.lq.ResSendActivityGiftToFriend);
  rpc sendClientMessage (.lq.ReqSendClientMessage) returns (.lq.ResCommon);
  rpc sendGiftToCharacter (.lq.ReqSendGiftToCharacter) returns (.lq.ResSendGiftToCharacter);
  rpc setAccountFavoriteHu (.lq.ReqSetAccountFavoriteHu) returns (.lq.ResCommon);
  rpc setActivityBuff (.lq.ReqSetActivityBuff) returns (.lq.ResActivityBuff);
  rpc setFriendRoomRandomBotChar (.lq.ReqSetFriendRoomRandomBotChar) returns (.lq.ResCommon);
  rpc setHiddenCharacter (.lq.ReqSetHiddenCharacter) returns (.lq.ResSetHiddenCharacter);
  rpc setLoadingImage (.lq.ReqSetLoadingImage) returns (.lq.ResCommon);
  rpc setRandomCharacter (.lq.ReqRandomCharacter) returns (.lq.ResCommon);
  rpc setVerifiedHidden (.lq.ReqSetVerifiedHidden) returns (.lq.ResCommon);
  rpc setVillageWorker (.lq.ReqSetVillageWorker) returns (.lq.ResSetVillageWorker);
  rpc shootActivityAttackEnemies (.lq.ReqShootActivityAttackEnemies) returns (.lq.ResShootActivityAttackEnemies);
  rpc shopPurchase (.lq.ReqShopPurchase) returns (.lq.ResShopPurchase);
  rpc signup (.lq.ReqSignupAccount) returns (.lq.ResSignupAccount);
  rpc signupCustomizedContest (.lq.ReqSignupCustomizedContest) returns (.lq.ResSignupCustomizedContest);
  rpc simV2ActivityEndMatch (.lq.ReqSimV2ActivityEndMatch) returns (.lq.ResSimV2ActivityEndMatch);
  rpc simV2ActivityFetchInfo (.lq.ReqSimV2ActivityFetchInfo) returns (.lq.ResSimV2ActivityFetchInfo);
  rpc simV2ActivityGiveUp (.lq.ReqSimV2ActivityGiveUp) returns (.lq.ResCommon);
  rpc simV2ActivitySelectEvent (.lq.ReqSimV2ActivitySelectEvent) returns (.lq.ResSimV2ActivitySelectEvent);
  rpc simV2ActivitySetUpgrade (.lq.ReqSimV2ActivitySetUpgrade) returns (.lq.ResCommon);
  rpc simV2ActivityStartMatch (.lq.ReqSimV2ActivityStartMatch) returns (.lq.ResSimV2ActivityStartMatch);
  rpc simV2ActivityStartSeason (.lq.ReqSimV2ActivityStartSeason) returns (.lq.ResSimV2ActivityStartSeason);
  rpc simV2ActivityTrain (.lq.ReqSimV2ActivityTrain) returns (.lq.ResSimV2ActivityTrain);
  rpc simulationActivityTrain (.lq.ReqSimulationActivityTrain) returns (.lq.ResSimulationActivityTrain);
  rpc snowballActivityFinishBattle (.lq.ReqSnowballActivityFinishBattle) returns (.lq.ResSnowballActivityFinishBattle);
  rpc snowballActivityReceiveReward (.lq.ReqSnowballActivityReceiveReward) returns (.lq.ResSnowballActivityReceiveReward);
  rpc snowballActivityStartBattle (.lq.ReqSnowballActivityStartBattle) returns (.lq.ResSnowballActivityStartBattle);
  rpc snowballActivityUpgrade (.lq.ReqSnowballActivityUpgrade) returns (.lq.ResSnowballActivityUpgrade);
  rpc solveGooglePayOrderV3 (.lq.ReqSolveGooglePlayOrderV3) returns (.lq.ResCommon);
  rpc solveGooglePlayOrder (.lq.ReqSolveGooglePlayOrder) returns (.lq.ResCommon);
  rpc startCustomizedContest (.lq.ReqStartCustomizedContest) returns (.lq.ResCommon);
  rpc startRoom (.lq.ReqRoomStart) returns (.lq.ResCommon);
  rpc startSimulationActivityGame (.lq.ReqStartSimulationActivityGame) returns (.lq.ResStartSimulationActivityGame);
  rpc startUnifiedMatch (.lq.ReqStartUnifiedMatch) returns (.lq.ResCommon);
  rpc startVillageTrip (.lq.ReqStartVillageTrip) returns (.lq.ResCommon);
  rpc stopCustomizedContest (.lq.ReqStopCustomizedContest) returns (.lq.ResCommon);
  rpc storyActivityReceiveAllFinishReward (.lq.ReqStoryActivityReceiveAllFinishReward) returns (.lq.ResStoryReward);
  rpc storyActivityReceiveEndingReward (.lq.ReqStoryActivityReceiveEndingReward) returns (.lq.ResStoryReward);
  rpc storyActivityReceiveFinishReward (.lq.ReqStoryActivityReceiveFinishReward) returns (.lq.ResStoryReward);
  rpc storyActivityUnlock (.lq.ReqStoryActivityUnlock) returns (.lq.ResCommon);
  rpc storyActivityUnlockEnding (.lq.ReqStoryActivityUnlockEnding) returns (.lq.ResCommon);
  rpc storyActivityUnlockEndingAndReceive (.lq.ReqStoryActivityUnlockEndingAndReceive) returns (.lq.ResStoryActivityUnlockEndingAndReceive);
  rpc submitQuestionnaire (.lq.ReqSubmitQuestionnaire) returns (.lq.ResCommon);
  rpc takeAttachmentFromMail (.lq.ReqTakeAttachment) returns (.lq.ResCommon);
  rpc taskRequest (.lq.ReqTaskRequest) returns (.lq.ResCommon);
  rpc unbindPhoneNumber (.lq.ReqUnbindPhoneNumber) returns (.lq.ResCommon);
  rpc unfollowCustomizedContest (.lq.ReqTargetCustomizedContest) returns (.lq.ResCommon);
  rpc unlockActivitySpot (.lq.ReqUnlockActivitySpot) returns (.lq.ResCommon);
  rpc unlockActivitySpotEnding (.lq.ReqUnlockActivitySpotEnding) returns (.lq.ResCommon);
  rpc updateAccountSettings (.lq.ReqUpdateAccountSettings) returns (.lq.ResCommon);
  rpc updateCharacterSort (.lq.ReqUpdateCharacterSort) returns (.lq.ResCommon);
  rpc updateClientValue (.lq.ReqUpdateClientValue) returns (.lq.ResCommon);
  rpc updateCommentSetting (.lq.ReqUpdateCommentSetting) returns (.lq.ResCommon);
  rpc updateIDCardInfo (.lq.ReqUpdateIDCardInfo) returns (.lq.ResCommon);
  rpc updateManagerCustomizedContest (.lq.ReqUpdateManagerCustomizedContest) returns (.lq.ResCommon);
  rpc updateReadComment (.lq.ReqUpdateReadComment) returns (.lq.ResCommon);
  rpc upgradeActivityBuff (.lq.ReqUpgradeActivityBuff) returns (.lq.ResActivityBuff);
  rpc upgradeActivityLevel (.lq.ReqUpgradeActivityLevel) returns (.lq.ResUpgradeActivityLevel);
  rpc upgradeChallenge (.lq.ReqCommon) returns (.lq.ResUpgradeChallenge);
  rpc upgradeCharacter (.lq.ReqUpgradeCharacter) returns (.lq.ResUpgradeCharacter);
  rpc upgradeVillageBuilding (.lq.ReqUpgradeVillageBuilding) returns (.lq.ResCommon);
  rpc useBagItem (.lq.ReqUseBagItem) returns (.lq.ResCommon);
  rpc useCommonView (.lq.ReqUseCommonView) returns (.lq.ResCommon);
  rpc useGiftCode (.lq.ReqUseGiftCode) returns (.lq.ResUseGiftCode);
  rpc useSpecialGiftCode (.lq.ReqUseGiftCode) returns (.lq.ResUseSpecialGiftCode);
  rpc useTitle (.lq.ReqUseTitle) returns (.lq.ResCommon);
  rpc userComplain (.lq.ReqUserComplain) returns (.lq.ResCommon);
  rpc verfifyCodeForSecure (.lq.ReqVerifyCodeForSecure) returns (.lq.ResVerfiyCodeForSecure);
  rpc verificationIAPOrder (.lq.ReqVerificationIAPOrder) returns (.lq.ResVerificationIAPOrder);
  rpc verifyMyCardOrder (.lq.ReqVerifyMyCardOrder) returns (.lq.ResCommon);
  rpc verifySteamOrder (.lq.ReqVerifySteamOrder) returns (.lq.ResCommon);
  rpc voteActivity (.lq.ReqVoteActivity) returns (.lq.ResVoteActivity);
  rpc yostarDeleteAccount (.lq.ReqYostarDeleteAccount) returns (.lq.ResYostarDeleteAccount);
}

service Route {
  rpc heartbeat (.lq.ReqHeartbeat) returns (.lq.ResHeartbeat);
  rpc requestConnection (.lq.ReqRequestConnection) returns (.lq.ResRequestConnection);
  rpc requestRouteChange (.lq.ReqRequestRouteChange) returns (.lq.ResRequestRouteChange);
}
